apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "fullname" . }}-backend
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          network/backend: "true"
          {{- include "selectorLabels" . | nindent 10 }}
  podSelector:
    matchLabels:
      network/backend: "true"
      {{- include "selectorLabels" . | nindent 6 }}
