apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "fullname" . }}-frontend
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          network/frontend: "true"
          {{- include "selectorLabels" . | nindent 10 }}
  - from:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - port: 80
      protocol: TCP
    - port: 9502
      protocol: TCP
  - from:
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/instance: ingress-nginx
          app.kubernetes.io/name: ingress-nginx
      podSelector:
        matchLabels:
          app.kubernetes.io/component: controller
          app.kubernetes.io/instance: ingress-nginx
          app.kubernetes.io/name: ingress-nginx
    {{- if and .Values.networkPolicy.wordpress.app .Values.networkPolicy.wordpress.env }}
    - namespaceSelector:
        matchLabels:
          app.gitlab.com/app: {{ .Values.networkPolicy.wordpress.app }}
          app.gitlab.com/env: {{ .Values.networkPolicy.wordpress.env }}
      podSelector:
        matchLabels:
          app.kubernetes.io/name: wordpress
    {{- end }}
    ports:
    - port: 80
      protocol: TCP
    - port: 8080
      protocol: TCP
    - port: 9502
      protocol: TCP
  podSelector:
    matchLabels:
      network/frontend: "true"
      {{- include "selectorLabels" . | nindent 6 }}
