apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fullname" . }}-galera-backup
type: Opaque
data: 
  aws_secret_access_key: {{ required "aws.secret.access.key must be set!" .Values.db.backup.aws.secret.access.key | b64enc | quote }}
  database_password: {{ required "mariadb.password must be set!" .Values.mariadb.password | b64enc | quote }}
  slack_webhook_url: {{ required "slack.webhook.url must be set" .Values.db.backup.slack.webhook.url | b64enc | quote }}