apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "fullname" . }}-mariadb
data:
  MYSQL_PASSWORD: {{ required "mariadb.password must be set!" .Values.mariadb.password | b64enc | quote }}
