apiVersion: v1
kind: Service
metadata:
  annotations:
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    component: mariadb
    {{- include "labels" . | nindent 4 }}
  name: {{ include "fullname" . }}-mariadb
spec:
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    component: mariadb
    {{- include "selectorLabels" . | nindent 4 }}
