apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fullname" . }}-mariadb
data:
  MYSQL_HOSTNAME: {{ include "fullname" . }}-mariadb
  MYSQL_USER: {{ include "fullname" . }}
  MYSQL_DATABASE: {{ include "fullname" . }}
