apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.deploymentAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    component: memcached
    {{- include "labels" . | nindent 4 }}
  name: {{ include "fullname" . }}-memcached
spec:
  replicas: 1
  selector:
    matchLabels:
      component: memcached
      {{- include "selectorLabels" . | nindent 6 }}
  strategy: {}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        network/backend: "true"
        component: memcached
        {{- include "selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - args:
            - -m 128
          image: library/memcached:alpine
          name: memcached
          ports:
            - containerPort: 11211
          resources: 
            requests:
              cpu: 10m
              memory: 100Mi
            limits:
              cpu: 50m
              memory: 100Mi
      restartPolicy: Always
