apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "fullname" . }}-php
data:
  REDIS_PASSWORD: {{ required ".Values.global.redis.password must be set!" .Values.global.redis.password | b64enc | quote }}
  {{- range $env, $value := .Values.php.secretEnvs }}
  {{ $env }}: {{ required (print ".Values.php.secretEnvs." $env " is required") $value | b64enc | quote }}
  {{- end }}
