{{- if semverCompare "<1.21.0-0" ( .Capabilities.KubeVersion.Version ) }}
apiVersion: policy/v1beta1
{{- else }}
apiVersion: policy/v1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "fullname" . }}-php
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      component: php
      app.kubernetes.io/name: {{ include "name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}