apiVersion: v1
kind: Service
metadata:
  annotations:
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    component: php
    {{- include "labels" . | nindent 4 }}
  name: {{ include "fullname" . }}-php
spec:
  ports:
    - name: php
      port: 80
      targetPort: php
    - name: ws
      port: 9502
      targetPort: ws
  selector:
    component: php
    {{- include "selectorLabels" . | nindent 4 }}
