apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fullname" . }}-php
  labels:
    app: {{ template "fullname" . }}
data:
  {{- range $env, $value := .Values.php.envs }}
  {{ $env }}: {{ $value | required (print ".Values.php.envs." $env " is required") | quote }}
  {{- end }}
