apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "fullname" . }}-redis
data:
  REDIS_PASSWORD: {{ required ".Values.global.redis.password must be set!" .Values.global.redis.password | b64enc | quote }}
