apiVersion: v1
kind: PersistentVolume
metadata:
  name: gallera-test-0
  # annotations:
  #   pv.kubernetes.io/provisioned-by: gallera-local
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/"
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: gallera-test-1
#   # annotations:
#   #   pv.kubernetes.io/provisioned-by: gallera-local
#   labels:
#     type: local
# spec:
#   storageClassName: gallera-local
#   capacity:
#     storage: 5Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/tmp/"
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: gallera-test-2
#   # annotations:
#   #   pv.kubernetes.io/provisioned-by: gallera-local
#   labels:
#     type: local
# spec:
#   storageClassName: gallera-local
#   capacity:
#     storage: 5Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/tmp/"