apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gallera-local
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain