apiVersion: batch/v1
kind: CronJob
metadata:
  name: gitlab-backup-sync
  namespace: gitlab-production
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          securityContext:
            runAsUser: 1000
            fsGroup: 1000
          volumes:
            - name: backups
              persistentVolumeClaim: 
                claimName: backups
            - name: toolbox-config
              projected:
                  sources:
                    - configMap:
                        name: gitlab-production-toolbox
                  defaultMode: 420
            - name: toolbox-tmp
              emptyDir: {}
            - name: init-toolbox-secrets
              projected:
                sources:
                  - secret:
                      name: gitlab-production-rails-secret
                      items:
                        - key: secrets.yml
                          path: rails-secrets/secrets.yml
                  - secret:
                      name: gitlab-production-gitlab-shell-secret
                      items:
                        - key: secret
                          path: shell/.gitlab_shell_secret
                  - secret:
                      name: gitlab-production-gitaly-secret
                      items:
                        - key: token
                          path: gitaly/gitaly_token
                  - secret:
                      name: gitlab-production-redis-secret
                      items:
                        - key: secret
                          path: redis/redis-password
                  - secret:
                      name: gitlab-production-postgresql-password
                      items:
                        - key: postgresql-password
                          path: postgres/psql-password-main
                  - secret:
                      name: gitlab-production-registry-secret
                      items:
                        - key: registry-auth.key
                          path: registry/gitlab-registry.key
                  - secret:
                      name: gitlab-production-registry-notification
                      items:
                        - key: secret
                          path: registry/notificationSecret
                  - secret:
                      name: gitlab-production-minio-secret
                      items:
                        - key: accesskey
                          path: minio/accesskey
                        - key: secretkey
                          path: minio/secretkey
                defaultMode: 256
            - name: toolbox-secrets
              emptyDir:
                medium: Memory
            - name: etc-ssl-certs
              emptyDir:
                medium: Memory
          initContainers:
            - name: certificates
              image: >-
                registry.gitlab.com/gitlab-org/build/cng/alpine-certificates:20191127-r2@sha256:367d437d024d7647432d67fb2442e3e5723af5930bad77d3535f4f8f4f8630d9
              resources:
                requests:
                  cpu: 50m
              volumeMounts:
                - name: etc-ssl-certs
                  mountPath: /etc/ssl/certs
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: IfNotPresent
            - name: configure
              image: >-
                registry.gitlab.com/gitlab-org/cloud-native/mirror/images/busybox:latest
              command:
                - sh
                - /config/configure
              resources:
                requests:
                  cpu: 50m
              volumeMounts:
                - name: toolbox-config
                  readOnly: true
                  mountPath: /config
                - name: init-toolbox-secrets
                  readOnly: true
                  mountPath: /init-config
                - name: toolbox-secrets
                  mountPath: /init-secrets
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: Always
          containers:
            - name: toolbox
              image: registry.gitlab.com/gitlab-org/build/cng/gitlab-toolbox-ee:v14.10.2
              args:
                - /bin/bash
                - '-c'
                - >-
                  cp -v -r -L /etc/gitlab/.s3cfg $HOME/.s3cfg && cd /srv/gitlab/tmp && rm -rf ./* && export BACKUP_FILENAME=$(s3cmd ls s3://gitlab-backups/ | awk '{print $4}' | awk -F"/gitlab-backups/" '{print$2}' | awk -F: '{print $1}') && s3cmd get $(s3cmd ls s3://gitlab-backups/ | awk '{print $4}') $BACKUP_FILENAME && s3cmd rm -rf s3://gitlab-backups/  && cp -v -r -L -f /etc/gitlab/.s3cfg.do $HOME/.s3cfg && s3cmd put $BACKUP_FILENAME s3://gpanel-gitlab-backups/$BACKUP_FILENAME
              env: 
                - name: ARTIFACTS_BUCKET_NAME
                  value: gitlab-artifacts
                - name: REGISTRY_BUCKET_NAME
                  value: registry
                - name: LFS_BUCKET_NAME
                  value: git-lfs
                - name: UPLOADS_BUCKET_NAME
                  value: gitlab-uploads
                - name: PACKAGES_BUCKET_NAME
                  value: gitlab-packages
                - name: EXTERNAL_DIFFS_BUCKET_NAME
                  value: gitlab-mr-diffs
                - name: TERRAFORM_STATE_BUCKET_NAME
                  value: gitlab-terraform-state
                - name: CI_SECURE_FILES_BUCKET_NAME
                  value: gitlab-ci-secure-files
                - name: BACKUP_BUCKET_NAME
                  value: gitlab-backups
                - name: BACKUP_BACKEND
                  value: s3
                - name: TMP_BUCKET_NAME
                  value: tmp
                - name: PAGES_BUCKET_NAME
                  value: gitlab-pages
                - name: GITALY_FEATURE_DEFAULT_ON
                  value: '1'
                - name: ENABLE_BOOTSNAP
                  value: '1'
                - name: CONFIG_TEMPLATE_DIRECTORY
                  value: /var/opt/gitlab/templates
                - name: CONFIG_DIRECTORY
                  value: /srv/gitlab/config
              resources:
                requests:
                  cpu: 50m
                  memory: 350M
              volumeMounts:
                - name: toolbox-config
                  mountPath: /var/opt/gitlab/templates
                - name: toolbox-config
                  mountPath: /srv/gitlab/config/initializers/smtp_settings.rb
                  subPath: smtp_settings.rb
                - name: backups
                  mountPath: /srv/gitlab/tmp/
                - name: toolbox-secrets
                  readOnly: true
                  mountPath: /etc/gitlab
                - name: toolbox-secrets
                  mountPath: /srv/gitlab/config/secrets.yml
                  subPath: rails-secrets/secrets.yml
                - name: toolbox-tmp
                  mountPath: /srv/gitlab/tmp
                - name: etc-ssl-certs
                  readOnly: true
                  mountPath: /etc/ssl/certs/
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: IfNotPresent
              